import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SABRAIN",
  description: "Generated by Sabah Naveed",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <div className="flex">
          <Navbar /> {/* Include the Navbar component here */}
          <main className="flex-1 ml-64 p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
