import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SABRAIN",
  description: "Generated by Sabah Naveed",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <div className="relative flex ">
          <Navbar className="fixed w-12 h-screen "/> 
          <main className="ml-36 w-full h-full ">{children}</main>
        </div>
      </body>
    </html>
  );
}
