import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/NavbarSab";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SABRAIN",
  description: "Generated by Sabah Naveed",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <div className="">
          <Navbar className=""/> 
          <main className="">{children}</main>
        </div>
      </body>
    </html>
  );
}
